-- ============================================================
-- Corrección: tabla recordatorio_salud incompleta + filas duplicadas.
--
-- Síntomas:
--   - En algunas cuentas no se pueden cambiar la frecuencia ni desactivar
--     los recordatorios (el valor "vuelve" al recargar).
--   - Error al consultar: "column r.frecuencia_valor does not exist".
--
-- Causa:
--   - La migración de columnas (frecuencia_valor/frecuencia_unidad) no se
--     aplicó en Supabase, por lo que la app no podía guardar los cambios.
--   - Además puede haber más de una fila por (id_usuario, tipo_recordatorio).
--
-- Cómo usar: supabase.com → SQL Editor → reemplazar el correo y ejecutar
-- TODO el bloque de abajo (es idempotente y seguro de repetir).
-- ============================================================

-- 0) ESQUEMA: crea la tabla si no existe y agrega las columnas nuevas.
create table if not exists public.recordatorio_salud (
  id_recordatorio    bigint generated by default as identity primary key,
  id_usuario         integer not null references public.usuario (id_usuario) on delete cascade,
  tipo_recordatorio  text    not null,
  frecuencia_minutos integer not null default 45,
  frecuencia_valor   integer not null default 0,
  frecuencia_unidad  text    not null default 'min',
  activo             boolean not null default false
);
alter table public.recordatorio_salud add column if not exists frecuencia_valor integer not null default 0;
alter table public.recordatorio_salud add column if not exists frecuencia_unidad text not null default 'min';

-- 1) DIAGNÓSTICO de la cuenta afectada. Reemplaza el correo si es necesario.
select r.id_recordatorio, r.tipo_recordatorio, r.frecuencia_minutos,
       r.frecuencia_valor, r.frecuencia_unidad, r.activo,
       u.id_usuario, u.correo, u.auth_user_id
from public.recordatorio_salud r
join public.usuario u on u.id_usuario = r.id_usuario
where u.correo = '2788218@clases.edu.sv'
order by r.tipo_recordatorio, r.id_recordatorio;

-- 2) LIMPIEZA de duplicados (todas las cuentas).
--    Deja una sola fila por (id_usuario, tipo_recordatorio): la de mayor id.
delete from public.recordatorio_salud r
where exists (
  select 1 from public.recordatorio_salud r2
  where r2.id_usuario = r.id_usuario
    and r2.tipo_recordatorio = r.tipo_recordatorio
    and r2.id_recordatorio > r.id_recordatorio
);

-- 3) UNIQUE: un solo recordatorio por (id_usuario, tipo_recordatorio).
--    Debe ejecutarse DESPUÉS de la limpieza del paso 2.
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'recordatorio_salud_usuario_tipo_unicos'
      and conrelid = 'public.recordatorio_salud'::regclass
  ) then
    alter table public.recordatorio_salud
      add constraint recordatorio_salud_usuario_tipo_unicos
      unique (id_usuario, tipo_recordatorio);
  end if;
end $$;

-- 4) VERIFICAR que no queden duplicados en ninguna cuenta (debe salir vacío).
select id_usuario, tipo_recordatorio, count(*) as n
from public.recordatorio_salud
group by id_usuario, tipo_recordatorio
having count(*) > 1;

-- 5) RLS: solo el dueño ve/modifica sus recordatorios (políticas idempotentes).
alter table public.recordatorio_salud enable row level security;

drop policy if exists "recordatorio_salud_select_own" on public.recordatorio_salud;
create policy "recordatorio_salud_select_own" on public.recordatorio_salud
  for select using (auth.uid() = (select auth_user_id from public.usuario where id_usuario = recordatorio_salud.id_usuario));

drop policy if exists "recordatorio_salud_insert_own" on public.recordatorio_salud;
create policy "recordatorio_salud_insert_own" on public.recordatorio_salud
  for insert with check (auth.uid() = (select auth_user_id from public.usuario where id_usuario = recordatorio_salud.id_usuario));

drop policy if exists "recordatorio_salud_update_own" on public.recordatorio_salud;
create policy "recordatorio_salud_update_own" on public.recordatorio_salud
  for update using (auth.uid() = (select auth_user_id from public.usuario where id_usuario = recordatorio_salud.id_usuario))
  with check (auth.uid() = (select auth_user_id from public.usuario where id_usuario = recordatorio_salud.id_usuario));

drop policy if exists "recordatorio_salud_delete_own" on public.recordatorio_salud;
create policy "recordatorio_salud_delete_own" on public.recordatorio_salud
  for delete using (auth.uid() = (select auth_user_id from public.usuario where id_usuario = recordatorio_salud.id_usuario));

-- 6) ENLACE RLS: si alguna fila de "usuario" tiene auth_user_id nulo, el
--    UPDATE/DELETE de sus recordatorios será bloqueado por las políticas.
--    Este backfill (idempotente) los enlaza con sus cuentas de Auth.
update public.usuario u
set auth_user_id = au.id
from auth.users au
where au.email = u.correo
  and u.auth_user_id is null;