-- Tabla de preferencias de recordatorios (salud + tareas).
-- Ejecutar en el SQL Editor de Supabase si la tabla no existe.

create table if not exists public.recordatorio_salud (
  id_recordatorio    bigint generated by default as identity primary key,
  id_usuario         integer not null references public.usuario (id_usuario) on delete cascade,
  tipo_recordatorio  text    not null,
  frecuencia_minutos integer not null default 45,
  frecuencia_valor   integer not null default 0,
  frecuencia_unidad  text    not null default 'min',
  activo             boolean not null default false
);

-- Migración para bases existentes (volver a ejecutar es seguro).
alter table public.recordatorio_salud add column if not exists frecuencia_valor integer not null default 0;
alter table public.recordatorio_salud add column if not exists frecuencia_unidad text not null default 'min';

-- Cada usuario puede tener un solo recordatorio por tipo (agua, descanso, tareas).
alter table public.recordatorio_salud
  add constraint recordatorio_salud_usuario_tipo_unicos
  unique (id_usuario, tipo_recordatorio);

-- RLS: solo el dueño puede ver y modificar sus recordatorios.
alter table public.recordatorio_salud enable row level security;

drop policy if exists "recordatorio_salud_select_own" on public.recordatorio_salud;
create policy "recordatorio_salud_select_own" on public.recordatorio_salud
  for select using (auth.uid() = (select auth_user_id from public.usuario where id_usuario = recordatorio_salud.id_usuario));

drop policy if exists "recordatorio_salud_insert_own" on public.recordatorio_salud;
create policy "recordatorio_salud_insert_own" on public.recordatorio_salud
  for insert with check (auth.uid() = (select auth_user_id from public.usuario where id_usuario = recordatorio_salud.id_usuario));

drop policy if exists "recordatorio_salud_update_own" on public.recordatorio_salud;
create policy "recordatorio_salud_update_own" on public.recordatorio_salud
  for update using (auth.uid() = (select auth_user_id from public.usuario where id_usuario = recordatorio_salud.id_usuario))
  with check (auth.uid() = (select auth_user_id from public.usuario where id_usuario = recordatorio_salud.id_usuario));

drop policy if exists "recordatorio_salud_delete_own" on public.recordatorio_salud;
create policy "recordatorio_salud_delete_own" on public.recordatorio_salud
  for delete using (auth.uid() = (select auth_user_id from public.usuario where id_usuario = recordatorio_salud.id_usuario));